shell = "/opt/homebrew/bin/fish"

[window]
decorations = "Buttonless"
dynamic_title = false
option_as_alt = "Both"

[mouse]
hide_when_typing = true

[font]
size = 18

[colors.primary]
background = "#0f0f0f"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
