shell = "/opt/homebrew/bin/fish"

[window]
decorations = "Buttonless"
dynamic_title = false
option_as_alt = "Both"

[mouse]
hide_when_typing = true

[font]
size = 18

[colors.primary]
background = "#0f0f0f"
