# monokai
# reference https://github.com/tanvirtin/monokai.nvim/blob/master/lua/monokai.lua

# base0 =       '#222426',
# base1 =       '#272a30',
# base2 =       '#26292C',
# base3 =       '#2E323C',
# base4 =       '#333842',
# base5 =       '#4d5154',
# base6 =       '#9ca0a4',
# base7 =       '#b1b1b1',
# base8 =       '#e3e3e1',
# border =      '#a1b5b1',
# brown =       '#504945',
# white =       '#f8f8f0',
# grey =        '#8F908A',
# black =       '#000000',
# pink =        '#f92672',
# green =       '#a6e22e',
# aqua =        '#66d9ef',
# yellow =      '#e6db74',
# orange =      '#fd971f',
# purple =      '#ae81ff',
# red =         '#e95678',
# diff_add =    '#3d5213',
# diff_remove = '#4a0f23',
# diff_change = '#27406b',
# diff_text =   '#23324d',

[colors.primary]
background = "#25292c"
foreground = '#c5c8c6'

[colors.normal]
black   = '#1d1f21'
red     = '#cc342b'
green   = '#198844'
yellow  = '#fba922'
blue    = '#3971ed'
magenta = '#a36ac7'
cyan    = '#3971ed'
white   = '#c5c8c6'

[colors.bright]
black   = '#969896'
red     = '#cc342b'
green   = '#198844'
yellow  = '#fba922'
blue    = '#3971ed'
magenta = '#a36ac7'
cyan    = '#3971ed'
white   = '#ffffff'
