# zaibatsu
# reference https://github.com/vim/vim/blob/master/runtime/colors/zaibatsu.vim

# Background: dark
# Color: background    #0e0024           16                black
# Color: darkred       #510039           52                darkred
# Color: darkgreen     #5faf00           70                darkgreen
# Color: darkyellow    #ffaf00           214               darkyellow
# Color: darkblue      #5f00d7           56                darkblue
# Color: darkmagenta   #d700ff           165               darkmagenta
# Color: darkcyan      #00afff           39                darkcyan
# Color: red           #ff5faf           205               red
# Color: green         #87ff00           118               green
# Color: yellow        #ffff5f           227               yellow
# Color: blue          #afafff           147               blue
# Color: magenta       #ffafff           219               magenta
# Color: cyan          #87ffff           123               cyan
# Color: white         #ffffff           231               white
# Color: neutral1      #D7D5DB           189               gray
# Color: neutral2      #AFAAB6           146               gray
# Color: neutral3      #878092           103               darkgray
# Color: neutral4      #5E556D           60                darkgray
# Color: neutral5      #362B49           237               darkgray
# Color: error         #d70000           160               red
# Color: visual        #5FD7FF           81                darkcyan

[colors.primary]
background = "#0e0024"
foreground = "#ffffff"

[colors.normal]
black = "#0e0024"
red = "#ff5faf"
green = "#87ff00"
yellow = "#ffff5f"
blue = "#afafff"
magenta = "#ffafff"
cyan = "#87ffff"
white = "#ffffff"

[colors.bright]
black = "#878092"
red = "#510039"
green = "#5faf00"
yellow = "#ffaf00"
blue = "#5f00d7"
magenta = "#d700ff"
cyan = "#00afff"
white = "#ffffff"
